/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { SDKCore } from "../core.js";
import { SDKOptions } from "../lib/config.js";
import type { ConsoleLogger } from "./console-logger.js";
import { createRegisterPrompt } from "./prompts.js";
import {
  createRegisterResource,
  createRegisterResourceTemplate,
} from "./resources.js";
import { MCPScope } from "./scopes.js";
import { createRegisterTool, registerDynamicTools } from "./tools.js";
import { tool$agentsGetV1OracleAgentsId } from "./tools/agentsGetV1OracleAgentsId.js";
import { tool$agentsGetV1OracleAgentsIdActivity } from "./tools/agentsGetV1OracleAgentsIdActivity.js";
import { tool$agentsGetV1OracleAgentsIdMetrics } from "./tools/agentsGetV1OracleAgentsIdMetrics.js";
import { tool$agentsGetV1OracleAgentsModelUsage } from "./tools/agentsGetV1OracleAgentsModelUsage.js";
import { tool$agentsGetV1OracleAgentsSearch } from "./tools/agentsGetV1OracleAgentsSearch.js";
import { tool$alertsDeleteV1OracleAlertsId } from "./tools/alertsDeleteV1OracleAlertsId.js";
import { tool$alertsGetV1OracleAlerts } from "./tools/alertsGetV1OracleAlerts.js";
import { tool$alertsPostV1OracleAlerts } from "./tools/alertsPostV1OracleAlerts.js";
import { tool$feedsGetV1OracleFeeds } from "./tools/feedsGetV1OracleFeeds.js";
import { tool$feedsGetV1OracleFeedsId } from "./tools/feedsGetV1OracleFeedsId.js";
import { tool$feedsGetV1OracleFeedsIdHistory } from "./tools/feedsGetV1OracleFeedsIdHistory.js";
import { tool$feedsGetV1OracleFeedsIdMethodology } from "./tools/feedsGetV1OracleFeedsIdMethodology.js";
import { tool$protocolsGetV1OracleProtocols } from "./tools/protocolsGetV1OracleProtocols.js";
import { tool$protocolsGetV1OracleProtocolsId } from "./tools/protocolsGetV1OracleProtocolsId.js";
import { tool$reportsPostV1OracleReportsVerify } from "./tools/reportsPostV1OracleReportsVerify.js";

export function createMCPServer(deps: {
  logger: ConsoleLogger;
  allowedTools?: string[] | undefined;
  dynamic?: boolean | undefined;
  scopes?: MCPScope[] | undefined;
  getSDK?: () => SDKCore;
  serverURL?: string | undefined;
  security?: SDKOptions["security"] | undefined;
  serverIdx?: SDKOptions["serverIdx"] | undefined;
}) {
  const server = new McpServer({
    name: "SDK",
    version: "0.0.2",
  });

  const getClient = deps.getSDK || (() =>
    new SDKCore({
      security: deps.security,
      serverURL: deps.serverURL,
      serverIdx: deps.serverIdx,
      debugLogger: deps.logger.level === "debug"
        ? {
          log: (...args) => console.log(...args),
          group: (...args) => console.group(...args),
          groupEnd: (...args) => console.groupEnd(...args),
        }
        : undefined,
    }));

  const scopes = new Set(deps.scopes);

  const allowedTools = deps.allowedTools && new Set(deps.allowedTools);
  const [tool, tools, toolMap] = createRegisterTool(
    deps.logger,
    server,
    getClient,
    scopes,
    allowedTools,
    deps.dynamic,
  );
  const resource = createRegisterResource(
    deps.logger,
    server,
    getClient,
    scopes,
  );
  const resourceTemplate = createRegisterResourceTemplate(
    deps.logger,
    server,
    getClient,
    scopes,
  );
  const prompt = createRegisterPrompt(deps.logger, server, getClient, scopes);
  const register = { tool, resource, resourceTemplate, prompt };
  void register; // suppress unused warnings

  tool(tool$feedsGetV1OracleFeeds);
  tool(tool$feedsGetV1OracleFeedsId);
  tool(tool$feedsGetV1OracleFeedsIdMethodology);
  tool(tool$feedsGetV1OracleFeedsIdHistory);
  tool(tool$reportsPostV1OracleReportsVerify);
  tool(tool$agentsGetV1OracleAgentsSearch);
  tool(tool$agentsGetV1OracleAgentsModelUsage);
  tool(tool$agentsGetV1OracleAgentsId);
  tool(tool$agentsGetV1OracleAgentsIdMetrics);
  tool(tool$agentsGetV1OracleAgentsIdActivity);
  tool(tool$protocolsGetV1OracleProtocols);
  tool(tool$protocolsGetV1OracleProtocolsId);
  tool(tool$alertsPostV1OracleAlerts);
  tool(tool$alertsGetV1OracleAlerts);
  tool(tool$alertsDeleteV1OracleAlertsId);

  if (deps.dynamic) {
    registerDynamicTools(deps.logger, server, getClient, toolMap, scopes);
  }

  return { server, tools };
}
