/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { agentsGetV1OracleAgentsSearch } from "../../funcs/agentsGetV1OracleAgentsSearch.js";
import { GetV1OracleAgentsSearchRequest$zodSchema } from "../../models/getv1oracleagentssearchop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetV1OracleAgentsSearchRequest$zodSchema.optional(),
};

export const tool$agentsGetV1OracleAgentsSearch: ToolDefinition<typeof args> = {
  name: "agents-get-v1-oracle-agents-search",
  description: `Find agents by wallet, protocol, ERC-8004 ID, or name.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await agentsGetV1OracleAgentsSearch(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
