/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { agentsGetV1OracleAgentsIdMetrics } from "../../funcs/agentsGetV1OracleAgentsIdMetrics.js";
import { GetV1OracleAgentsIdMetricsRequest$zodSchema } from "../../models/getv1oracleagentsidmetricsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetV1OracleAgentsIdMetricsRequest$zodSchema,
};

export const tool$agentsGetV1OracleAgentsIdMetrics: ToolDefinition<
  typeof args
> = {
  name: "agents-get-v1-oracle-agents-id-metrics",
  description:
    `Full agent dossier — wallet/evidence/protocol breakdowns. Requires pro tier.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await agentsGetV1OracleAgentsIdMetrics(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
