/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { agentsGetV1OracleAgentsIdActivity } from "../../funcs/agentsGetV1OracleAgentsIdActivity.js";
import { GetV1OracleAgentsIdActivityRequest$zodSchema } from "../../models/getv1oracleagentsidactivityop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetV1OracleAgentsIdActivityRequest$zodSchema,
};

export const tool$agentsGetV1OracleAgentsIdActivity: ToolDefinition<
  typeof args
> = {
  name: "agents-get-v1-oracle-agents-id-activity",
  description: `Agent activity feed — grouped with oracle_agent_deep_metrics.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await agentsGetV1OracleAgentsIdActivity(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
