/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { agentsGetV1OracleAgentsId } from "../../funcs/agentsGetV1OracleAgentsId.js";
import { GetV1OracleAgentsIdRequest$zodSchema } from "../../models/getv1oracleagentsidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetV1OracleAgentsIdRequest$zodSchema,
};

export const tool$agentsGetV1OracleAgentsId: ToolDefinition<typeof args> = {
  name: "agents-get-v1-oracle-agents-id",
  description: `Agent profile — wallets, protocols, reputation, stats.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await agentsGetV1OracleAgentsId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
