/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { agentsGetV1OracleAgentsModelUsage } from "../../funcs/agentsGetV1OracleAgentsModelUsage.js";
import { GetV1OracleAgentsModelUsageRequest$zodSchema } from "../../models/getv1oracleagentsmodelusageop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetV1OracleAgentsModelUsageRequest$zodSchema.optional(),
};

export const tool$agentsGetV1OracleAgentsModelUsage: ToolDefinition<
  typeof args
> = {
  name: "agents-get-v1-oracle-agents-model-usage",
  description:
    `LLM model/provider distribution across the agent economy. Empty results mean no data, not an error.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await agentsGetV1OracleAgentsModelUsage(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
