/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { alertsDeleteV1OracleAlertsId } from "../../funcs/alertsDeleteV1OracleAlertsId.js";
import { DeleteV1OracleAlertsIdRequest$zodSchema } from "../../models/deletev1oraclealertsidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteV1OracleAlertsIdRequest$zodSchema,
};

export const tool$alertsDeleteV1OracleAlertsId: ToolDefinition<typeof args> = {
  name: "alerts-delete-v1-oracle-alerts-id",
  description: `Delete a webhook alert subscription.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await alertsDeleteV1OracleAlertsId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
