/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { alertsGetV1OracleAlerts } from "../../funcs/alertsGetV1OracleAlerts.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$alertsGetV1OracleAlerts: ToolDefinition = {
  name: "alerts-get-v1-oracle-alerts",
  description:
    `List active webhook alert subscriptions for the authenticated tenant.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  tool: async (client, ctx) => {
    const [result] = await alertsGetV1OracleAlerts(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
