/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { alertsPostV1OracleAlerts } from "../../funcs/alertsPostV1OracleAlerts.js";
import { PostV1OracleAlertsRequest$zodSchema } from "../../models/postv1oraclealertsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PostV1OracleAlertsRequest$zodSchema,
};

export const tool$alertsPostV1OracleAlerts: ToolDefinition<typeof args> = {
  name: "alerts-post-v1-oracle-alerts",
  description:
    `Create a webhook alert subscription for feed updates, agent events, or reports. Requires pro tier.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await alertsPostV1OracleAlerts(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
