/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { feedsGetV1OracleFeeds } from "../../funcs/feedsGetV1OracleFeeds.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$feedsGetV1OracleFeeds: ToolDefinition = {
  name: "feeds-get-v1-oracle-feeds",
  description:
    `Get current state of the agent economy — AEGDP, AAI, APRI feed values with confidence and freshness.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  tool: async (client, ctx) => {
    const [result] = await feedsGetV1OracleFeeds(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
