/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { feedsGetV1OracleFeedsId } from "../../funcs/feedsGetV1OracleFeedsId.js";
import { GetV1OracleFeedsIdRequest$zodSchema } from "../../models/getv1oraclefeedsidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetV1OracleFeedsIdRequest$zodSchema,
};

export const tool$feedsGetV1OracleFeedsId: ToolDefinition<typeof args> = {
  name: "feeds-get-v1-oracle-feeds-id",
  description:
    `Deep dive on a single oracle feed with its latest value and methodology context.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await feedsGetV1OracleFeedsId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
