/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { feedsGetV1OracleFeedsIdHistory } from "../../funcs/feedsGetV1OracleFeedsIdHistory.js";
import { GetV1OracleFeedsIdHistoryRequest$zodSchema } from "../../models/getv1oraclefeedsidhistoryop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetV1OracleFeedsIdHistoryRequest$zodSchema,
};

export const tool$feedsGetV1OracleFeedsIdHistory: ToolDefinition<typeof args> =
  {
    name: "feeds-get-v1-oracle-feeds-id-history",
    description:
      `Time-series feed values for trend analysis. Empty results mean no data for the period, not an error.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await feedsGetV1OracleFeedsIdHistory(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
