/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { feedsGetV1OracleFeedsIdMethodology } from "../../funcs/feedsGetV1OracleFeedsIdMethodology.js";
import { GetV1OracleFeedsIdMethodologyRequest$zodSchema } from "../../models/getv1oraclefeedsidmethodologyop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetV1OracleFeedsIdMethodologyRequest$zodSchema,
};

export const tool$feedsGetV1OracleFeedsIdMethodology: ToolDefinition<
  typeof args
> = {
  name: "feeds-get-v1-oracle-feeds-id-methodology",
  description: `Feed methodology detail — grouped with oracle_feed_value.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await feedsGetV1OracleFeedsIdMethodology(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
