/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { protocolsGetV1OracleProtocolsId } from "../../funcs/protocolsGetV1OracleProtocolsId.js";
import { GetV1OracleProtocolsIdRequest$zodSchema } from "../../models/getv1oracleprotocolsidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetV1OracleProtocolsIdRequest$zodSchema,
};

export const tool$protocolsGetV1OracleProtocolsId: ToolDefinition<typeof args> =
  {
    name: "protocols-get-v1-oracle-protocols-id",
    description:
      `Protocol detail with agent/wallet counts — grouped with oracle_protocol_stats.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await protocolsGetV1OracleProtocolsId(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
