/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { protocolsGetV1OracleProtocols } from "../../funcs/protocolsGetV1OracleProtocols.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$protocolsGetV1OracleProtocols: ToolDefinition = {
  name: "protocols-get-v1-oracle-protocols",
  description: `Protocol listing with chain support and status.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  tool: async (client, ctx) => {
    const [result] = await protocolsGetV1OracleProtocols(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
