/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { reportsPostV1OracleReportsVerify } from "../../funcs/reportsPostV1OracleReportsVerify.js";
import { PostV1OracleReportsVerifyRequest$zodSchema } from "../../models/postv1oraclereportsverifyop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PostV1OracleReportsVerifyRequest$zodSchema,
};

export const tool$reportsPostV1OracleReportsVerify: ToolDefinition<
  typeof args
> = {
  name: "reports-post-v1-oracle-reports-verify",
  description:
    `Verify signed oracle report — Ed25519 signature + payload integrity + publication status.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await reportsPostV1OracleReportsVerify(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
