/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type Def0 = {
  type: string;
  title: string;
  status: number;
  detail?: string | undefined;
  instance?: string | undefined;
  code?: string | undefined;
};

export const Def0$zodSchema: z.ZodType<Def0> = z.object({
  code: z.string().optional(),
  detail: z.string().optional(),
  instance: z.string().optional(),
  status: z.int(),
  title: z.string(),
  type: z.string(),
});
