/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DeleteV1OracleAlertsIdRequest = { id: string };

export const DeleteV1OracleAlertsIdRequest$zodSchema: z.ZodType<
  DeleteV1OracleAlertsIdRequest
> = z.object({
  id: z.string().describe("Alert subscription ID"),
});
