/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Def0, Def0$zodSchema } from "./def0.js";

export type GetV1OracleFeedsIdRequest = { id: string };

export const GetV1OracleFeedsIdRequest$zodSchema: z.ZodType<
  GetV1OracleFeedsIdRequest
> = z.object({
  id: z.string().describe("Feed identifier (aegdp, aai, apri)"),
});

export type GetV1OracleFeedsIdFeed = {
  id: string;
  name: string;
  description: string;
  version: number;
  methodology_url: string;
};

export const GetV1OracleFeedsIdFeed$zodSchema: z.ZodType<
  GetV1OracleFeedsIdFeed
> = z.object({
  description: z.string(),
  id: z.string(),
  methodology_url: z.string(),
  name: z.string(),
  version: z.int(),
});

export type Latest = {
  feed_id: string;
  value: string;
  confidence: number;
  completeness: number;
  freshness_ms: number;
  staleness_risk: string;
  computed_at: string;
  signer: string;
  signature: string;
};

export const Latest$zodSchema: z.ZodType<Latest> = z.object({
  completeness: z.number(),
  computed_at: z.string(),
  confidence: z.number(),
  feed_id: z.string(),
  freshness_ms: z.int(),
  signature: z.string(),
  signer: z.string(),
  staleness_risk: z.string(),
  value: z.string(),
});

/**
 * Default Response
 */
export type GetV1OracleFeedsIdResponseBody = {
  feed: GetV1OracleFeedsIdFeed;
  latest: Latest | null;
  methodology_url: string;
};

export const GetV1OracleFeedsIdResponseBody$zodSchema: z.ZodType<
  GetV1OracleFeedsIdResponseBody
> = z.object({
  feed: z.lazy(() => GetV1OracleFeedsIdFeed$zodSchema),
  latest: z.lazy(() => Latest$zodSchema).nullable(),
  methodology_url: z.string(),
}).describe("Default Response");

export type GetV1OracleFeedsIdResponse = GetV1OracleFeedsIdResponseBody | Def0;

export const GetV1OracleFeedsIdResponse$zodSchema: z.ZodType<
  GetV1OracleFeedsIdResponse
> = z.union([
  z.lazy(() => GetV1OracleFeedsIdResponseBody$zodSchema),
  Def0$zodSchema,
]);
