/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Def0, Def0$zodSchema } from "./def0.js";

export type GetV1OracleProtocolsIdMetricsRequest = { id: string };

export const GetV1OracleProtocolsIdMetricsRequest$zodSchema: z.ZodType<
  GetV1OracleProtocolsIdMetricsRequest
> = z.object({
  id: z.string(),
});

export type Agents = { total: number; by_link_type: { [k: string]: number } };

export const Agents$zodSchema: z.ZodType<Agents> = z.object({
  by_link_type: z.record(z.string(), z.int()),
  total: z.int(),
});

export type GetV1OracleProtocolsIdMetricsWallets = {
  total: number;
  by_chain: { [k: string]: number };
};

export const GetV1OracleProtocolsIdMetricsWallets$zodSchema: z.ZodType<
  GetV1OracleProtocolsIdMetricsWallets
> = z.object({
  by_chain: z.record(z.string(), z.int()),
  total: z.int(),
});

export type GetV1OracleProtocolsIdMetricsEvidence = {
  total: number;
  by_type: { [k: string]: number };
};

export const GetV1OracleProtocolsIdMetricsEvidence$zodSchema: z.ZodType<
  GetV1OracleProtocolsIdMetricsEvidence
> = z.object({
  by_type: z.record(z.string(), z.int()),
  total: z.int(),
});

export type GetV1OracleProtocolsIdMetricsData = {
  protocol_id: string;
  agents: Agents;
  wallets: GetV1OracleProtocolsIdMetricsWallets;
  evidence: GetV1OracleProtocolsIdMetricsEvidence;
  recent_registrations_7d: number;
  active_conflicts: number;
};

export const GetV1OracleProtocolsIdMetricsData$zodSchema: z.ZodType<
  GetV1OracleProtocolsIdMetricsData
> = z.object({
  active_conflicts: z.int(),
  agents: z.lazy(() => Agents$zodSchema),
  evidence: z.lazy(() => GetV1OracleProtocolsIdMetricsEvidence$zodSchema),
  protocol_id: z.string(),
  recent_registrations_7d: z.int(),
  wallets: z.lazy(() => GetV1OracleProtocolsIdMetricsWallets$zodSchema),
});

/**
 * Default Response
 */
export type GetV1OracleProtocolsIdMetricsResponseBody = {
  data: GetV1OracleProtocolsIdMetricsData;
};

export const GetV1OracleProtocolsIdMetricsResponseBody$zodSchema: z.ZodType<
  GetV1OracleProtocolsIdMetricsResponseBody
> = z.object({
  data: z.lazy(() => GetV1OracleProtocolsIdMetricsData$zodSchema),
}).describe("Default Response");

export type GetV1OracleProtocolsIdMetricsResponse =
  | Def0
  | GetV1OracleProtocolsIdMetricsResponseBody;

export const GetV1OracleProtocolsIdMetricsResponse$zodSchema: z.ZodType<
  GetV1OracleProtocolsIdMetricsResponse
> = z.union([
  Def0$zodSchema,
  z.lazy(() => GetV1OracleProtocolsIdMetricsResponseBody$zodSchema),
]);
