/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Def0, Def0$zodSchema } from "./def0.js";

export type GetV1OracleAgentsIdMetricsRequest = { id: string };

export const GetV1OracleAgentsIdMetricsRequest$zodSchema: z.ZodType<
  GetV1OracleAgentsIdMetricsRequest
> = z.object({
  id: z.string(),
});

export type GetV1OracleAgentsIdMetricsWallets = {
  total: number;
  by_chain: { [k: string]: number };
  by_link_type: { [k: string]: number };
};

export const GetV1OracleAgentsIdMetricsWallets$zodSchema: z.ZodType<
  GetV1OracleAgentsIdMetricsWallets
> = z.object({
  by_chain: z.record(z.string(), z.int()),
  by_link_type: z.record(z.string(), z.int()),
  total: z.int(),
});

export type GetV1OracleAgentsIdMetricsEvidence = {
  total: number;
  by_type: { [k: string]: number };
};

export const GetV1OracleAgentsIdMetricsEvidence$zodSchema: z.ZodType<
  GetV1OracleAgentsIdMetricsEvidence
> = z.object({
  by_type: z.record(z.string(), z.int()),
  total: z.int(),
});

export type Protocols = { total: number; list: Array<string> };

export const Protocols$zodSchema: z.ZodType<Protocols> = z.object({
  list: z.array(z.string()),
  total: z.int(),
});

export type Conflicts = { active: number; resolved: number };

export const Conflicts$zodSchema: z.ZodType<Conflicts> = z.object({
  active: z.int(),
  resolved: z.int(),
});

export type GetV1OracleAgentsIdMetricsData = {
  agent_id: string;
  wallets: GetV1OracleAgentsIdMetricsWallets;
  evidence: GetV1OracleAgentsIdMetricsEvidence;
  protocols: Protocols;
  conflicts: Conflicts;
  first_seen: string;
  last_active: string;
};

export const GetV1OracleAgentsIdMetricsData$zodSchema: z.ZodType<
  GetV1OracleAgentsIdMetricsData
> = z.object({
  agent_id: z.string(),
  conflicts: z.lazy(() => Conflicts$zodSchema),
  evidence: z.lazy(() => GetV1OracleAgentsIdMetricsEvidence$zodSchema),
  first_seen: z.string(),
  last_active: z.string(),
  protocols: z.lazy(() => Protocols$zodSchema),
  wallets: z.lazy(() => GetV1OracleAgentsIdMetricsWallets$zodSchema),
});

/**
 * Default Response
 */
export type GetV1OracleAgentsIdMetricsResponseBody = {
  data: GetV1OracleAgentsIdMetricsData;
};

export const GetV1OracleAgentsIdMetricsResponseBody$zodSchema: z.ZodType<
  GetV1OracleAgentsIdMetricsResponseBody
> = z.object({
  data: z.lazy(() => GetV1OracleAgentsIdMetricsData$zodSchema),
}).describe("Default Response");

export type GetV1OracleAgentsIdMetricsResponse =
  | Def0
  | GetV1OracleAgentsIdMetricsResponseBody;

export const GetV1OracleAgentsIdMetricsResponse$zodSchema: z.ZodType<
  GetV1OracleAgentsIdMetricsResponse
> = z.union([
  Def0$zodSchema,
  z.lazy(() => GetV1OracleAgentsIdMetricsResponseBody$zodSchema),
]);
