/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { Def0, Def0$zodSchema } from "./def0.js";

export const GetV1OracleAgentsModelUsagePeriod30d = {
  Thirtyd: "30d",
} as const;
export type GetV1OracleAgentsModelUsagePeriod30d = ClosedEnum<
  typeof GetV1OracleAgentsModelUsagePeriod30d
>;

export const GetV1OracleAgentsModelUsagePeriod30d$zodSchema = z.enum([
  "30d",
]);

export const GetV1OracleAgentsModelUsagePeriod7d = {
  Sevend: "7d",
} as const;
export type GetV1OracleAgentsModelUsagePeriod7d = ClosedEnum<
  typeof GetV1OracleAgentsModelUsagePeriod7d
>;

export const GetV1OracleAgentsModelUsagePeriod7d$zodSchema = z.enum([
  "7d",
]);

export const GetV1OracleAgentsModelUsagePeriod1d = {
  Oned: "1d",
} as const;
export type GetV1OracleAgentsModelUsagePeriod1d = ClosedEnum<
  typeof GetV1OracleAgentsModelUsagePeriod1d
>;

export const GetV1OracleAgentsModelUsagePeriod1d$zodSchema = z.enum([
  "1d",
]);

export type GetV1OracleAgentsModelUsagePeriodUnion =
  | GetV1OracleAgentsModelUsagePeriod1d
  | GetV1OracleAgentsModelUsagePeriod7d
  | GetV1OracleAgentsModelUsagePeriod30d;

export const GetV1OracleAgentsModelUsagePeriodUnion$zodSchema: z.ZodType<
  GetV1OracleAgentsModelUsagePeriodUnion
> = z.union([
  GetV1OracleAgentsModelUsagePeriod1d$zodSchema,
  GetV1OracleAgentsModelUsagePeriod7d$zodSchema,
  GetV1OracleAgentsModelUsagePeriod30d$zodSchema,
]);

export type GetV1OracleAgentsModelUsageRequest = {
  period?:
    | GetV1OracleAgentsModelUsagePeriod1d
    | GetV1OracleAgentsModelUsagePeriod7d
    | GetV1OracleAgentsModelUsagePeriod30d
    | undefined;
  limit?: number | undefined;
};

export const GetV1OracleAgentsModelUsageRequest$zodSchema: z.ZodType<
  GetV1OracleAgentsModelUsageRequest
> = z.object({
  limit: z.int().default(20),
  period: z.union([
    GetV1OracleAgentsModelUsagePeriod1d$zodSchema,
    GetV1OracleAgentsModelUsagePeriod7d$zodSchema,
    GetV1OracleAgentsModelUsagePeriod30d$zodSchema,
  ]).optional(),
});

export type Model = {
  model_id: string;
  provider: string;
  event_count: number;
  pct: number;
};

export const Model$zodSchema: z.ZodType<Model> = z.object({
  event_count: z.int(),
  model_id: z.string(),
  pct: z.number(),
  provider: z.string(),
});

export type GetV1OracleAgentsModelUsageData = {
  period: string;
  has_data: boolean;
  models: Array<Model>;
  total_events: number;
};

export const GetV1OracleAgentsModelUsageData$zodSchema: z.ZodType<
  GetV1OracleAgentsModelUsageData
> = z.object({
  has_data: z.boolean(),
  models: z.array(z.lazy(() => Model$zodSchema)),
  period: z.string(),
  total_events: z.int(),
});

/**
 * Default Response
 */
export type GetV1OracleAgentsModelUsageResponseBody = {
  data: GetV1OracleAgentsModelUsageData;
};

export const GetV1OracleAgentsModelUsageResponseBody$zodSchema: z.ZodType<
  GetV1OracleAgentsModelUsageResponseBody
> = z.object({
  data: z.lazy(() => GetV1OracleAgentsModelUsageData$zodSchema),
}).describe("Default Response");

export type GetV1OracleAgentsModelUsageResponse =
  | Def0
  | GetV1OracleAgentsModelUsageResponseBody;

export const GetV1OracleAgentsModelUsageResponse$zodSchema: z.ZodType<
  GetV1OracleAgentsModelUsageResponse
> = z.union([
  Def0$zodSchema,
  z.lazy(() => GetV1OracleAgentsModelUsageResponseBody$zodSchema),
]);
