/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type GetV1OracleStreamRequest = {
  token?: string | undefined;
  channels: string;
  filter?: string | undefined;
};

export const GetV1OracleStreamRequest$zodSchema: z.ZodType<
  GetV1OracleStreamRequest
> = z.object({
  channels: z.string().describe(
    "Comma-separated channel names: feeds,agent_events,reports",
  ),
  filter: z.string().describe("JSON filter: {\"feeds\":[\"aegdp\"]}")
    .optional(),
  token: z.string().describe("Short-lived JWT from POST /stream/token")
    .optional(),
});
