/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Def0, Def0$zodSchema } from "./def0.js";

export type GetV1OracleProtocolsIdRequest = { id: string };

export const GetV1OracleProtocolsIdRequest$zodSchema: z.ZodType<
  GetV1OracleProtocolsIdRequest
> = z.object({
  id: z.string(),
});

export type GetV1OracleProtocolsIdStats = {
  agent_count: number;
  wallet_count: number;
};

export const GetV1OracleProtocolsIdStats$zodSchema: z.ZodType<
  GetV1OracleProtocolsIdStats
> = z.object({
  agent_count: z.int(),
  wallet_count: z.int(),
});

export type GetV1OracleProtocolsIdData = {
  id: string;
  name: string;
  chains: Array<string>;
  status: string;
  stats: GetV1OracleProtocolsIdStats;
};

export const GetV1OracleProtocolsIdData$zodSchema: z.ZodType<
  GetV1OracleProtocolsIdData
> = z.object({
  chains: z.array(z.string()),
  id: z.string(),
  name: z.string(),
  stats: z.lazy(() => GetV1OracleProtocolsIdStats$zodSchema),
  status: z.string(),
});

/**
 * Default Response
 */
export type GetV1OracleProtocolsIdResponseBody = {
  data: GetV1OracleProtocolsIdData;
};

export const GetV1OracleProtocolsIdResponseBody$zodSchema: z.ZodType<
  GetV1OracleProtocolsIdResponseBody
> = z.object({
  data: z.lazy(() => GetV1OracleProtocolsIdData$zodSchema),
}).describe("Default Response");

export type GetV1OracleProtocolsIdResponse =
  | Def0
  | GetV1OracleProtocolsIdResponseBody;

export const GetV1OracleProtocolsIdResponse$zodSchema: z.ZodType<
  GetV1OracleProtocolsIdResponse
> = z.union([
  Def0$zodSchema,
  z.lazy(() => GetV1OracleProtocolsIdResponseBody$zodSchema),
]);
