/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { Def0, Def0$zodSchema } from "./def0.js";

export type GetV1OracleAgentsIdActivityRequest = {
  limit?: number | undefined;
  cursor?: string | undefined;
  id: string;
};

export const GetV1OracleAgentsIdActivityRequest$zodSchema: z.ZodType<
  GetV1OracleAgentsIdActivityRequest
> = z.object({
  cursor: z.string().optional(),
  id: z.string(),
  limit: z.int().default(20),
});

export const TypeWalletLinked = {
  WalletLinked: "wallet_linked",
} as const;
export type TypeWalletLinked = ClosedEnum<typeof TypeWalletLinked>;

export const TypeWalletLinked$zodSchema = z.enum([
  "wallet_linked",
]);

export const TypeConflictOpened = {
  ConflictOpened: "conflict_opened",
} as const;
export type TypeConflictOpened = ClosedEnum<typeof TypeConflictOpened>;

export const TypeConflictOpened$zodSchema = z.enum([
  "conflict_opened",
]);

export const TypeEvidenceAdded = {
  EvidenceAdded: "evidence_added",
} as const;
export type TypeEvidenceAdded = ClosedEnum<typeof TypeEvidenceAdded>;

export const TypeEvidenceAdded$zodSchema = z.enum([
  "evidence_added",
]);

export type Type = TypeEvidenceAdded | TypeConflictOpened | TypeWalletLinked;

export const Type$zodSchema: z.ZodType<Type> = z.union([
  TypeEvidenceAdded$zodSchema,
  TypeConflictOpened$zodSchema,
  TypeWalletLinked$zodSchema,
]);

export type GetV1OracleAgentsIdActivityData = {
  type: TypeEvidenceAdded | TypeConflictOpened | TypeWalletLinked;
  timestamp: string;
  detail: { [k: string]: any };
};

export const GetV1OracleAgentsIdActivityData$zodSchema: z.ZodType<
  GetV1OracleAgentsIdActivityData
> = z.object({
  detail: z.record(z.string(), z.any()),
  timestamp: z.string(),
  type: z.union([
    TypeEvidenceAdded$zodSchema,
    TypeConflictOpened$zodSchema,
    TypeWalletLinked$zodSchema,
  ]),
});

export type GetV1OracleAgentsIdActivityPagination = {
  next_cursor: string | null;
  has_more: boolean;
  limit: number;
};

export const GetV1OracleAgentsIdActivityPagination$zodSchema: z.ZodType<
  GetV1OracleAgentsIdActivityPagination
> = z.object({
  has_more: z.boolean(),
  limit: z.int(),
  next_cursor: z.string().nullable(),
});

/**
 * Default Response
 */
export type GetV1OracleAgentsIdActivityResponseBody = {
  data: Array<GetV1OracleAgentsIdActivityData>;
  pagination: GetV1OracleAgentsIdActivityPagination;
};

export const GetV1OracleAgentsIdActivityResponseBody$zodSchema: z.ZodType<
  GetV1OracleAgentsIdActivityResponseBody
> = z.object({
  data: z.array(z.lazy(() => GetV1OracleAgentsIdActivityData$zodSchema)),
  pagination: z.lazy(() => GetV1OracleAgentsIdActivityPagination$zodSchema),
}).describe("Default Response");

export type GetV1OracleAgentsIdActivityResponse =
  | Def0
  | GetV1OracleAgentsIdActivityResponseBody;

export const GetV1OracleAgentsIdActivityResponse$zodSchema: z.ZodType<
  GetV1OracleAgentsIdActivityResponse
> = z.union([
  Def0$zodSchema,
  z.lazy(() => GetV1OracleAgentsIdActivityResponseBody$zodSchema),
]);
