/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Def0, Def0$zodSchema } from "./def0.js";

export type GetV1OracleAgentsSearchRequest = {
  limit?: number | undefined;
  cursor?: string | undefined;
  wallet?: string | undefined;
  chain?: string | undefined;
  protocol?: string | undefined;
  protocol_id?: string | undefined;
  erc8004_id?: string | undefined;
  q?: string | undefined;
};

export const GetV1OracleAgentsSearchRequest$zodSchema: z.ZodType<
  GetV1OracleAgentsSearchRequest
> = z.object({
  chain: z.string().optional(),
  cursor: z.string().optional(),
  erc8004_id: z.string().optional(),
  limit: z.int().default(20),
  protocol: z.string().optional(),
  protocol_id: z.string().optional(),
  q: z.string().optional(),
  wallet: z.string().optional(),
});

export type GetV1OracleAgentsSearchData = {
  id: string;
  display_name: string | null;
  erc8004_id: string | null;
  created_at: string;
};

export const GetV1OracleAgentsSearchData$zodSchema: z.ZodType<
  GetV1OracleAgentsSearchData
> = z.object({
  created_at: z.string(),
  display_name: z.string().nullable(),
  erc8004_id: z.string().nullable(),
  id: z.string(),
});

export type GetV1OracleAgentsSearchPagination = {
  next_cursor: string | null;
  has_more: boolean;
  limit: number;
};

export const GetV1OracleAgentsSearchPagination$zodSchema: z.ZodType<
  GetV1OracleAgentsSearchPagination
> = z.object({
  has_more: z.boolean(),
  limit: z.int(),
  next_cursor: z.string().nullable(),
});

/**
 * Default Response
 */
export type GetV1OracleAgentsSearchResponseBody = {
  data: Array<GetV1OracleAgentsSearchData>;
  pagination: GetV1OracleAgentsSearchPagination;
};

export const GetV1OracleAgentsSearchResponseBody$zodSchema: z.ZodType<
  GetV1OracleAgentsSearchResponseBody
> = z.object({
  data: z.array(z.lazy(() => GetV1OracleAgentsSearchData$zodSchema)),
  pagination: z.lazy(() => GetV1OracleAgentsSearchPagination$zodSchema),
}).describe("Default Response");

export type GetV1OracleAgentsSearchResponse =
  | Def0
  | GetV1OracleAgentsSearchResponseBody;

export const GetV1OracleAgentsSearchResponse$zodSchema: z.ZodType<
  GetV1OracleAgentsSearchResponse
> = z.union([
  Def0$zodSchema,
  z.lazy(() => GetV1OracleAgentsSearchResponseBody$zodSchema),
]);
