/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Def0, Def0$zodSchema } from "./def0.js";

export type GetV1OracleAgentsIdRequest = { id: string };

export const GetV1OracleAgentsIdRequest$zodSchema: z.ZodType<
  GetV1OracleAgentsIdRequest
> = z.object({
  id: z.string(),
});

export type Reputation = { score: number; updated_at: string };

export const Reputation$zodSchema: z.ZodType<Reputation> = z.object({
  score: z.number(),
  updated_at: z.string(),
});

export type Wallet = {
  chain: string;
  address: string;
  link_type: string;
  confidence: number;
};

export const Wallet$zodSchema: z.ZodType<Wallet> = z.object({
  address: z.string(),
  chain: z.string(),
  confidence: z.number(),
  link_type: z.string(),
});

export type Protocol = {
  protocol: string;
  protocol_id: string;
  link_type: string;
  confidence: number;
};

export const Protocol$zodSchema: z.ZodType<Protocol> = z.object({
  confidence: z.number(),
  link_type: z.string(),
  protocol: z.string(),
  protocol_id: z.string(),
});

export type GetV1OracleAgentsIdStats = {
  wallet_count: number;
  protocol_count: number;
  evidence_count: number;
};

export const GetV1OracleAgentsIdStats$zodSchema: z.ZodType<
  GetV1OracleAgentsIdStats
> = z.object({
  evidence_count: z.int(),
  protocol_count: z.int(),
  wallet_count: z.int(),
});

export type AgentProfile = {
  id: string;
  display_name: string | null;
  erc8004_id: string | null;
  lucid_tenant: string | null;
  reputation: Reputation | null;
  wallets: Array<Wallet>;
  protocols: Array<Protocol>;
  stats: GetV1OracleAgentsIdStats;
  created_at: string;
  updated_at: string;
};

export const AgentProfile$zodSchema: z.ZodType<AgentProfile> = z.object({
  created_at: z.string(),
  display_name: z.string().nullable(),
  erc8004_id: z.string().nullable(),
  id: z.string(),
  lucid_tenant: z.string().nullable(),
  protocols: z.array(z.lazy(() => Protocol$zodSchema)),
  reputation: z.lazy(() => Reputation$zodSchema).nullable(),
  stats: z.lazy(() => GetV1OracleAgentsIdStats$zodSchema),
  updated_at: z.string(),
  wallets: z.array(z.lazy(() => Wallet$zodSchema)),
});

/**
 * Default Response
 */
export type GetV1OracleAgentsIdResponseBody = { data: AgentProfile };

export const GetV1OracleAgentsIdResponseBody$zodSchema: z.ZodType<
  GetV1OracleAgentsIdResponseBody
> = z.object({
  data: z.lazy(() => AgentProfile$zodSchema),
}).describe("Default Response");

export type GetV1OracleAgentsIdResponse =
  | Def0
  | GetV1OracleAgentsIdResponseBody;

export const GetV1OracleAgentsIdResponse$zodSchema: z.ZodType<
  GetV1OracleAgentsIdResponse
> = z.union([
  Def0$zodSchema,
  z.lazy(() => GetV1OracleAgentsIdResponseBody$zodSchema),
]);
