/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { Def0, Def0$zodSchema } from "./def0.js";

export const GetV1OracleAlertsChannelReports = {
  Reports: "reports",
} as const;
export type GetV1OracleAlertsChannelReports = ClosedEnum<
  typeof GetV1OracleAlertsChannelReports
>;

export const GetV1OracleAlertsChannelReports$zodSchema = z.enum([
  "reports",
]);

export const GetV1OracleAlertsChannelAgentEvents = {
  AgentEvents: "agent_events",
} as const;
export type GetV1OracleAlertsChannelAgentEvents = ClosedEnum<
  typeof GetV1OracleAlertsChannelAgentEvents
>;

export const GetV1OracleAlertsChannelAgentEvents$zodSchema = z.enum([
  "agent_events",
]);

export const GetV1OracleAlertsChannelFeeds = {
  Feeds: "feeds",
} as const;
export type GetV1OracleAlertsChannelFeeds = ClosedEnum<
  typeof GetV1OracleAlertsChannelFeeds
>;

export const GetV1OracleAlertsChannelFeeds$zodSchema = z.enum([
  "feeds",
]);

export type GetV1OracleAlertsChannelUnion =
  | GetV1OracleAlertsChannelFeeds
  | GetV1OracleAlertsChannelAgentEvents
  | GetV1OracleAlertsChannelReports;

export const GetV1OracleAlertsChannelUnion$zodSchema: z.ZodType<
  GetV1OracleAlertsChannelUnion
> = z.union([
  GetV1OracleAlertsChannelFeeds$zodSchema,
  GetV1OracleAlertsChannelAgentEvents$zodSchema,
  GetV1OracleAlertsChannelReports$zodSchema,
]);

export const GetV1OracleAlertsOperatorNeq = {
  Neq: "neq",
} as const;
export type GetV1OracleAlertsOperatorNeq = ClosedEnum<
  typeof GetV1OracleAlertsOperatorNeq
>;

export const GetV1OracleAlertsOperatorNeq$zodSchema = z.enum([
  "neq",
]);

export const GetV1OracleAlertsOperatorEq = {
  Eq: "eq",
} as const;
export type GetV1OracleAlertsOperatorEq = ClosedEnum<
  typeof GetV1OracleAlertsOperatorEq
>;

export const GetV1OracleAlertsOperatorEq$zodSchema = z.enum([
  "eq",
]);

export const GetV1OracleAlertsOperatorLte = {
  Lte: "lte",
} as const;
export type GetV1OracleAlertsOperatorLte = ClosedEnum<
  typeof GetV1OracleAlertsOperatorLte
>;

export const GetV1OracleAlertsOperatorLte$zodSchema = z.enum([
  "lte",
]);

export const GetV1OracleAlertsOperatorLt = {
  Lt: "lt",
} as const;
export type GetV1OracleAlertsOperatorLt = ClosedEnum<
  typeof GetV1OracleAlertsOperatorLt
>;

export const GetV1OracleAlertsOperatorLt$zodSchema = z.enum([
  "lt",
]);

export const GetV1OracleAlertsOperatorGte = {
  Gte: "gte",
} as const;
export type GetV1OracleAlertsOperatorGte = ClosedEnum<
  typeof GetV1OracleAlertsOperatorGte
>;

export const GetV1OracleAlertsOperatorGte$zodSchema = z.enum([
  "gte",
]);

export const GetV1OracleAlertsOperatorGt = {
  Gt: "gt",
} as const;
export type GetV1OracleAlertsOperatorGt = ClosedEnum<
  typeof GetV1OracleAlertsOperatorGt
>;

export const GetV1OracleAlertsOperatorGt$zodSchema = z.enum([
  "gt",
]);

export type GetV1OracleAlertsOperatorUnion =
  | GetV1OracleAlertsOperatorGt
  | GetV1OracleAlertsOperatorGte
  | GetV1OracleAlertsOperatorLt
  | GetV1OracleAlertsOperatorLte
  | GetV1OracleAlertsOperatorEq
  | GetV1OracleAlertsOperatorNeq;

export const GetV1OracleAlertsOperatorUnion$zodSchema: z.ZodType<
  GetV1OracleAlertsOperatorUnion
> = z.union([
  GetV1OracleAlertsOperatorGt$zodSchema,
  GetV1OracleAlertsOperatorGte$zodSchema,
  GetV1OracleAlertsOperatorLt$zodSchema,
  GetV1OracleAlertsOperatorLte$zodSchema,
  GetV1OracleAlertsOperatorEq$zodSchema,
  GetV1OracleAlertsOperatorNeq$zodSchema,
]);

export type GetV1OracleAlertsConditions = {
  field: string;
  operator:
    | GetV1OracleAlertsOperatorGt
    | GetV1OracleAlertsOperatorGte
    | GetV1OracleAlertsOperatorLt
    | GetV1OracleAlertsOperatorLte
    | GetV1OracleAlertsOperatorEq
    | GetV1OracleAlertsOperatorNeq;
  threshold: number;
};

export const GetV1OracleAlertsConditions$zodSchema: z.ZodType<
  GetV1OracleAlertsConditions
> = z.object({
  field: z.string(),
  operator: z.union([
    GetV1OracleAlertsOperatorGt$zodSchema,
    GetV1OracleAlertsOperatorGte$zodSchema,
    GetV1OracleAlertsOperatorLt$zodSchema,
    GetV1OracleAlertsOperatorLte$zodSchema,
    GetV1OracleAlertsOperatorEq$zodSchema,
    GetV1OracleAlertsOperatorNeq$zodSchema,
  ]),
  threshold: z.number(),
});

export type GetV1OracleAlertsData = {
  id: string;
  channel:
    | GetV1OracleAlertsChannelFeeds
    | GetV1OracleAlertsChannelAgentEvents
    | GetV1OracleAlertsChannelReports;
  url: string;
  filter?: { [k: string]: Array<string> } | undefined;
  conditions?: GetV1OracleAlertsConditions | undefined;
  active: boolean;
  created_at: string;
};

export const GetV1OracleAlertsData$zodSchema: z.ZodType<GetV1OracleAlertsData> =
  z.object({
    active: z.boolean(),
    channel: z.union([
      GetV1OracleAlertsChannelFeeds$zodSchema,
      GetV1OracleAlertsChannelAgentEvents$zodSchema,
      GetV1OracleAlertsChannelReports$zodSchema,
    ]),
    conditions: z.lazy(() => GetV1OracleAlertsConditions$zodSchema).optional(),
    created_at: z.string(),
    filter: z.record(z.string(), z.array(z.string())).optional(),
    id: z.string(),
    url: z.string(),
  });

/**
 * Default Response
 */
export type GetV1OracleAlertsResponseBody = {
  data: Array<GetV1OracleAlertsData>;
};

export const GetV1OracleAlertsResponseBody$zodSchema: z.ZodType<
  GetV1OracleAlertsResponseBody
> = z.object({
  data: z.array(z.lazy(() => GetV1OracleAlertsData$zodSchema)),
}).describe("Default Response");

export type GetV1OracleAlertsResponse = Def0 | GetV1OracleAlertsResponseBody;

export const GetV1OracleAlertsResponse$zodSchema: z.ZodType<
  GetV1OracleAlertsResponse
> = z.union([
  Def0$zodSchema,
  z.lazy(() => GetV1OracleAlertsResponseBody$zodSchema),
]);
