/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const SortNewest = {
  Newest: "newest",
} as const;
export type SortNewest = ClosedEnum<typeof SortNewest>;

export const SortNewest$zodSchema = z.enum([
  "newest",
]);

export const SortEvidenceCount = {
  EvidenceCount: "evidence_count",
} as const;
export type SortEvidenceCount = ClosedEnum<typeof SortEvidenceCount>;

export const SortEvidenceCount$zodSchema = z.enum([
  "evidence_count",
]);

export const SortProtocolCount = {
  ProtocolCount: "protocol_count",
} as const;
export type SortProtocolCount = ClosedEnum<typeof SortProtocolCount>;

export const SortProtocolCount$zodSchema = z.enum([
  "protocol_count",
]);

export const SortWalletCount = {
  WalletCount: "wallet_count",
} as const;
export type SortWalletCount = ClosedEnum<typeof SortWalletCount>;

export const SortWalletCount$zodSchema = z.enum([
  "wallet_count",
]);

export type Sort =
  | SortWalletCount
  | SortProtocolCount
  | SortEvidenceCount
  | SortNewest;

export const Sort$zodSchema: z.ZodType<Sort> = z.union([
  SortWalletCount$zodSchema,
  SortProtocolCount$zodSchema,
  SortEvidenceCount$zodSchema,
  SortNewest$zodSchema,
]);

export type GetV1OracleAgentsLeaderboardRequest = {
  limit?: number | undefined;
  cursor?: string | undefined;
  sort?:
    | SortWalletCount
    | SortProtocolCount
    | SortEvidenceCount
    | SortNewest
    | undefined;
};

export const GetV1OracleAgentsLeaderboardRequest$zodSchema: z.ZodType<
  GetV1OracleAgentsLeaderboardRequest
> = z.object({
  cursor: z.string().optional(),
  limit: z.int().default(20),
  sort: z.union([
    SortWalletCount$zodSchema,
    SortProtocolCount$zodSchema,
    SortEvidenceCount$zodSchema,
    SortNewest$zodSchema,
  ]).optional(),
});

export type GetV1OracleAgentsLeaderboardData = {
  id: string;
  display_name: string | null;
  erc8004_id: string | null;
  wallet_count: number;
  protocol_count: number;
  evidence_count: number;
  created_at: string;
};

export const GetV1OracleAgentsLeaderboardData$zodSchema: z.ZodType<
  GetV1OracleAgentsLeaderboardData
> = z.object({
  created_at: z.string(),
  display_name: z.string().nullable(),
  erc8004_id: z.string().nullable(),
  evidence_count: z.int(),
  id: z.string(),
  protocol_count: z.int(),
  wallet_count: z.int(),
});

export type GetV1OracleAgentsLeaderboardPagination = {
  next_cursor: string | null;
  has_more: boolean;
  limit: number;
};

export const GetV1OracleAgentsLeaderboardPagination$zodSchema: z.ZodType<
  GetV1OracleAgentsLeaderboardPagination
> = z.object({
  has_more: z.boolean(),
  limit: z.int(),
  next_cursor: z.string().nullable(),
});

/**
 * Default Response
 */
export type GetV1OracleAgentsLeaderboardResponse = {
  data: Array<GetV1OracleAgentsLeaderboardData>;
  pagination: GetV1OracleAgentsLeaderboardPagination;
};

export const GetV1OracleAgentsLeaderboardResponse$zodSchema: z.ZodType<
  GetV1OracleAgentsLeaderboardResponse
> = z.object({
  data: z.array(z.lazy(() => GetV1OracleAgentsLeaderboardData$zodSchema)),
  pagination: z.lazy(() => GetV1OracleAgentsLeaderboardPagination$zodSchema),
}).describe("Default Response");
