/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type GetV1OracleReportsLatestFeed = {
  feed_id: string;
  value: string;
  confidence: number;
  completeness: number;
  freshness_ms: number;
  staleness_risk: string;
  computed_at: string;
  signer: string;
  signature: string;
};

export const GetV1OracleReportsLatestFeed$zodSchema: z.ZodType<
  GetV1OracleReportsLatestFeed
> = z.object({
  completeness: z.number(),
  computed_at: z.string(),
  confidence: z.number(),
  feed_id: z.string(),
  freshness_ms: z.int(),
  signature: z.string(),
  signer: z.string(),
  staleness_risk: z.string(),
  value: z.string(),
});

export type GetV1OracleReportsLatestReport = {
  feeds: Array<GetV1OracleReportsLatestFeed>;
};

export const GetV1OracleReportsLatestReport$zodSchema: z.ZodType<
  GetV1OracleReportsLatestReport
> = z.object({
  feeds: z.array(z.lazy(() => GetV1OracleReportsLatestFeed$zodSchema)),
});

/**
 * Default Response
 */
export type GetV1OracleReportsLatestResponse = {
  report: GetV1OracleReportsLatestReport | null;
};

export const GetV1OracleReportsLatestResponse$zodSchema: z.ZodType<
  GetV1OracleReportsLatestResponse
> = z.object({
  report: z.lazy(() => GetV1OracleReportsLatestReport$zodSchema).nullable(),
}).describe("Default Response");
