/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { Def0, Def0$zodSchema } from "./def0.js";

export const Period90d = {
  Ninetyd: "90d",
} as const;
export type Period90d = ClosedEnum<typeof Period90d>;

export const Period90d$zodSchema = z.enum([
  "90d",
]);

export const GetV1OracleFeedsIdHistoryPeriod30d = {
  Thirtyd: "30d",
} as const;
export type GetV1OracleFeedsIdHistoryPeriod30d = ClosedEnum<
  typeof GetV1OracleFeedsIdHistoryPeriod30d
>;

export const GetV1OracleFeedsIdHistoryPeriod30d$zodSchema = z.enum([
  "30d",
]);

export const GetV1OracleFeedsIdHistoryPeriod7d = {
  Sevend: "7d",
} as const;
export type GetV1OracleFeedsIdHistoryPeriod7d = ClosedEnum<
  typeof GetV1OracleFeedsIdHistoryPeriod7d
>;

export const GetV1OracleFeedsIdHistoryPeriod7d$zodSchema = z.enum([
  "7d",
]);

export const GetV1OracleFeedsIdHistoryPeriod1d = {
  Oned: "1d",
} as const;
export type GetV1OracleFeedsIdHistoryPeriod1d = ClosedEnum<
  typeof GetV1OracleFeedsIdHistoryPeriod1d
>;

export const GetV1OracleFeedsIdHistoryPeriod1d$zodSchema = z.enum([
  "1d",
]);

export type GetV1OracleFeedsIdHistoryPeriodUnion =
  | GetV1OracleFeedsIdHistoryPeriod1d
  | GetV1OracleFeedsIdHistoryPeriod7d
  | GetV1OracleFeedsIdHistoryPeriod30d
  | Period90d;

export const GetV1OracleFeedsIdHistoryPeriodUnion$zodSchema: z.ZodType<
  GetV1OracleFeedsIdHistoryPeriodUnion
> = z.union([
  GetV1OracleFeedsIdHistoryPeriod1d$zodSchema,
  GetV1OracleFeedsIdHistoryPeriod7d$zodSchema,
  GetV1OracleFeedsIdHistoryPeriod30d$zodSchema,
  Period90d$zodSchema,
]);

export const Interval1d = {
  Oned: "1d",
} as const;
export type Interval1d = ClosedEnum<typeof Interval1d>;

export const Interval1d$zodSchema = z.enum([
  "1d",
]);

export const Interval1h = {
  Oneh: "1h",
} as const;
export type Interval1h = ClosedEnum<typeof Interval1h>;

export const Interval1h$zodSchema = z.enum([
  "1h",
]);

export const Interval1m = {
  Onem: "1m",
} as const;
export type Interval1m = ClosedEnum<typeof Interval1m>;

export const Interval1m$zodSchema = z.enum([
  "1m",
]);

export type Interval = Interval1m | Interval1h | Interval1d;

export const Interval$zodSchema: z.ZodType<Interval> = z.union([
  Interval1m$zodSchema,
  Interval1h$zodSchema,
  Interval1d$zodSchema,
]);

export type GetV1OracleFeedsIdHistoryRequest = {
  period?:
    | GetV1OracleFeedsIdHistoryPeriod1d
    | GetV1OracleFeedsIdHistoryPeriod7d
    | GetV1OracleFeedsIdHistoryPeriod30d
    | Period90d
    | undefined;
  interval?: Interval1m | Interval1h | Interval1d | undefined;
  id: string;
};

export const GetV1OracleFeedsIdHistoryRequest$zodSchema: z.ZodType<
  GetV1OracleFeedsIdHistoryRequest
> = z.object({
  id: z.string().describe("Feed identifier (aegdp, aai, apri)"),
  interval: z.union([
    Interval1m$zodSchema,
    Interval1h$zodSchema,
    Interval1d$zodSchema,
  ]).optional(),
  period: z.union([
    GetV1OracleFeedsIdHistoryPeriod1d$zodSchema,
    GetV1OracleFeedsIdHistoryPeriod7d$zodSchema,
    GetV1OracleFeedsIdHistoryPeriod30d$zodSchema,
    Period90d$zodSchema,
  ]).optional(),
});

export type Point = { timestamp: string; value: string; confidence: number };

export const Point$zodSchema: z.ZodType<Point> = z.object({
  confidence: z.number(),
  timestamp: z.string(),
  value: z.string(),
});

export type GetV1OracleFeedsIdHistoryData = {
  feed_id: string;
  period: string;
  interval: string;
  has_data: boolean;
  points: Array<Point>;
};

export const GetV1OracleFeedsIdHistoryData$zodSchema: z.ZodType<
  GetV1OracleFeedsIdHistoryData
> = z.object({
  feed_id: z.string(),
  has_data: z.boolean(),
  interval: z.string(),
  period: z.string(),
  points: z.array(z.lazy(() => Point$zodSchema)),
});

/**
 * Default Response
 */
export type GetV1OracleFeedsIdHistoryResponseBody = {
  data: GetV1OracleFeedsIdHistoryData;
};

export const GetV1OracleFeedsIdHistoryResponseBody$zodSchema: z.ZodType<
  GetV1OracleFeedsIdHistoryResponseBody
> = z.object({
  data: z.lazy(() => GetV1OracleFeedsIdHistoryData$zodSchema),
}).describe("Default Response");

export type GetV1OracleFeedsIdHistoryResponse =
  | Def0
  | GetV1OracleFeedsIdHistoryResponseBody;

export const GetV1OracleFeedsIdHistoryResponse$zodSchema: z.ZodType<
  GetV1OracleFeedsIdHistoryResponse
> = z.union([
  Def0$zodSchema,
  z.lazy(() => GetV1OracleFeedsIdHistoryResponseBody$zodSchema),
]);
