/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type LatestValue = {
  feed_id: string;
  value: string;
  confidence: number;
  completeness: number;
  freshness_ms: number;
  staleness_risk: string;
  computed_at: string;
  signer: string;
  signature: string;
};

export const LatestValue$zodSchema: z.ZodType<LatestValue> = z.object({
  completeness: z.number(),
  computed_at: z.string(),
  confidence: z.number(),
  feed_id: z.string(),
  freshness_ms: z.int(),
  signature: z.string(),
  signer: z.string(),
  staleness_risk: z.string(),
  value: z.string(),
});

export type GetV1OracleFeedsFeed = {
  id: string;
  name: string;
  description: string;
  version: number;
  methodology_url: string;
  update_interval_ms: number;
  deviation_threshold_bps: number;
  latest_value: LatestValue | null;
};

export const GetV1OracleFeedsFeed$zodSchema: z.ZodType<GetV1OracleFeedsFeed> = z
  .object({
    description: z.string(),
    deviation_threshold_bps: z.int(),
    id: z.string(),
    latest_value: z.lazy(() => LatestValue$zodSchema).nullable(),
    methodology_url: z.string(),
    name: z.string(),
    update_interval_ms: z.int(),
    version: z.int(),
  });

/**
 * Default Response
 */
export type GetV1OracleFeedsResponse = { feeds: Array<GetV1OracleFeedsFeed> };

export const GetV1OracleFeedsResponse$zodSchema: z.ZodType<
  GetV1OracleFeedsResponse
> = z.object({
  feeds: z.array(z.lazy(() => GetV1OracleFeedsFeed$zodSchema)),
}).describe("Default Response");
