/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type GetV1OracleProtocolsData = {
  id: string;
  name: string;
  chains: Array<string>;
  status: string;
};

export const GetV1OracleProtocolsData$zodSchema: z.ZodType<
  GetV1OracleProtocolsData
> = z.object({
  chains: z.array(z.string()),
  id: z.string(),
  name: z.string(),
  status: z.string(),
});

/**
 * Default Response
 */
export type GetV1OracleProtocolsResponse = {
  data: Array<GetV1OracleProtocolsData>;
};

export const GetV1OracleProtocolsResponse$zodSchema: z.ZodType<
  GetV1OracleProtocolsResponse
> = z.object({
  data: z.array(z.lazy(() => GetV1OracleProtocolsData$zodSchema)),
}).describe("Default Response");
