/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Def0, Def0$zodSchema } from "./def0.js";

export type GetV1OracleFeedsIdMethodologyRequest = { id: string };

export const GetV1OracleFeedsIdMethodologyRequest$zodSchema: z.ZodType<
  GetV1OracleFeedsIdMethodologyRequest
> = z.object({
  id: z.string().describe("Feed identifier (aegdp, aai, apri)"),
});

export type ConfidenceFormula = {
  version: number;
  weights: { [k: string]: number };
};

export const ConfidenceFormula$zodSchema: z.ZodType<ConfidenceFormula> = z
  .object({
    version: z.int(),
    weights: z.record(z.string(), z.number()),
  });

/**
 * Default Response
 */
export type GetV1OracleFeedsIdMethodologyResponseBody = {
  feed_id: string;
  version: number;
  name: string;
  description: string;
  update_interval_ms: number;
  deviation_threshold_bps: number;
  confidence_formula: ConfidenceFormula;
  computation?: { [k: string]: any } | undefined;
  canonical_json_version?: string | undefined;
};

export const GetV1OracleFeedsIdMethodologyResponseBody$zodSchema: z.ZodType<
  GetV1OracleFeedsIdMethodologyResponseBody
> = z.object({
  canonical_json_version: z.string().optional(),
  computation: z.record(z.string(), z.any()).optional(),
  confidence_formula: z.lazy(() => ConfidenceFormula$zodSchema),
  description: z.string(),
  deviation_threshold_bps: z.int(),
  feed_id: z.string(),
  name: z.string(),
  update_interval_ms: z.int(),
  version: z.int(),
}).describe("Default Response");

export type GetV1OracleFeedsIdMethodologyResponse =
  | GetV1OracleFeedsIdMethodologyResponseBody
  | Def0;

export const GetV1OracleFeedsIdMethodologyResponse$zodSchema: z.ZodType<
  GetV1OracleFeedsIdMethodologyResponse
> = z.union([
  z.lazy(() => GetV1OracleFeedsIdMethodologyResponseBody$zodSchema),
  Def0$zodSchema,
]);
