/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { Def0, Def0$zodSchema } from "./def0.js";

export const ChannelReportsRequest = {
  Reports: "reports",
} as const;
export type ChannelReportsRequest = ClosedEnum<typeof ChannelReportsRequest>;

export const ChannelReportsRequest$zodSchema = z.enum([
  "reports",
]);

export const ChannelAgentEventsRequest = {
  AgentEvents: "agent_events",
} as const;
export type ChannelAgentEventsRequest = ClosedEnum<
  typeof ChannelAgentEventsRequest
>;

export const ChannelAgentEventsRequest$zodSchema = z.enum([
  "agent_events",
]);

export const ChannelFeedsRequest = {
  Feeds: "feeds",
} as const;
export type ChannelFeedsRequest = ClosedEnum<typeof ChannelFeedsRequest>;

export const ChannelFeedsRequest$zodSchema = z.enum([
  "feeds",
]);

export type ChannelRequestUnion =
  | ChannelFeedsRequest
  | ChannelAgentEventsRequest
  | ChannelReportsRequest;

export const ChannelRequestUnion$zodSchema: z.ZodType<ChannelRequestUnion> = z
  .union([
    ChannelFeedsRequest$zodSchema,
    ChannelAgentEventsRequest$zodSchema,
    ChannelReportsRequest$zodSchema,
  ]);

export const OperatorNeqRequest = {
  Neq: "neq",
} as const;
export type OperatorNeqRequest = ClosedEnum<typeof OperatorNeqRequest>;

export const OperatorNeqRequest$zodSchema = z.enum([
  "neq",
]);

export const OperatorEqRequest = {
  Eq: "eq",
} as const;
export type OperatorEqRequest = ClosedEnum<typeof OperatorEqRequest>;

export const OperatorEqRequest$zodSchema = z.enum([
  "eq",
]);

export const OperatorLteRequest = {
  Lte: "lte",
} as const;
export type OperatorLteRequest = ClosedEnum<typeof OperatorLteRequest>;

export const OperatorLteRequest$zodSchema = z.enum([
  "lte",
]);

export const OperatorLtRequest = {
  Lt: "lt",
} as const;
export type OperatorLtRequest = ClosedEnum<typeof OperatorLtRequest>;

export const OperatorLtRequest$zodSchema = z.enum([
  "lt",
]);

export const OperatorGteRequest = {
  Gte: "gte",
} as const;
export type OperatorGteRequest = ClosedEnum<typeof OperatorGteRequest>;

export const OperatorGteRequest$zodSchema = z.enum([
  "gte",
]);

export const OperatorGtRequest = {
  Gt: "gt",
} as const;
export type OperatorGtRequest = ClosedEnum<typeof OperatorGtRequest>;

export const OperatorGtRequest$zodSchema = z.enum([
  "gt",
]);

export type OperatorRequestUnion =
  | OperatorGtRequest
  | OperatorGteRequest
  | OperatorLtRequest
  | OperatorLteRequest
  | OperatorEqRequest
  | OperatorNeqRequest;

export const OperatorRequestUnion$zodSchema: z.ZodType<OperatorRequestUnion> = z
  .union([
    OperatorGtRequest$zodSchema,
    OperatorGteRequest$zodSchema,
    OperatorLtRequest$zodSchema,
    OperatorLteRequest$zodSchema,
    OperatorEqRequest$zodSchema,
    OperatorNeqRequest$zodSchema,
  ]);

export type ConditionsRequest = {
  field: string;
  operator:
    | OperatorGtRequest
    | OperatorGteRequest
    | OperatorLtRequest
    | OperatorLteRequest
    | OperatorEqRequest
    | OperatorNeqRequest;
  threshold: number;
};

export const ConditionsRequest$zodSchema: z.ZodType<ConditionsRequest> = z
  .object({
    field: z.string(),
    operator: z.union([
      OperatorGtRequest$zodSchema,
      OperatorGteRequest$zodSchema,
      OperatorLtRequest$zodSchema,
      OperatorLteRequest$zodSchema,
      OperatorEqRequest$zodSchema,
      OperatorNeqRequest$zodSchema,
    ]),
    threshold: z.number(),
  });

export type PostV1OracleAlertsRequest = {
  channel:
    | ChannelFeedsRequest
    | ChannelAgentEventsRequest
    | ChannelReportsRequest;
  url: string;
  filter?: { [k: string]: Array<string> } | undefined;
  conditions?: ConditionsRequest | undefined;
};

export const PostV1OracleAlertsRequest$zodSchema: z.ZodType<
  PostV1OracleAlertsRequest
> = z.object({
  channel: z.union([
    ChannelFeedsRequest$zodSchema,
    ChannelAgentEventsRequest$zodSchema,
    ChannelReportsRequest$zodSchema,
  ]),
  conditions: z.lazy(() => ConditionsRequest$zodSchema).optional(),
  filter: z.record(z.string(), z.array(z.string())).optional(),
  url: z.string(),
});

export const ChannelSubscriptionReports = {
  Reports: "reports",
} as const;
export type ChannelSubscriptionReports = ClosedEnum<
  typeof ChannelSubscriptionReports
>;

export const ChannelSubscriptionReports$zodSchema = z.enum([
  "reports",
]);

export const ChannelSubscriptionAgentEvents = {
  AgentEvents: "agent_events",
} as const;
export type ChannelSubscriptionAgentEvents = ClosedEnum<
  typeof ChannelSubscriptionAgentEvents
>;

export const ChannelSubscriptionAgentEvents$zodSchema = z.enum([
  "agent_events",
]);

export const ChannelSubscriptionFeeds = {
  Feeds: "feeds",
} as const;
export type ChannelSubscriptionFeeds = ClosedEnum<
  typeof ChannelSubscriptionFeeds
>;

export const ChannelSubscriptionFeeds$zodSchema = z.enum([
  "feeds",
]);

export type SubscriptionChannelUnion =
  | ChannelSubscriptionFeeds
  | ChannelSubscriptionAgentEvents
  | ChannelSubscriptionReports;

export const SubscriptionChannelUnion$zodSchema: z.ZodType<
  SubscriptionChannelUnion
> = z.union([
  ChannelSubscriptionFeeds$zodSchema,
  ChannelSubscriptionAgentEvents$zodSchema,
  ChannelSubscriptionReports$zodSchema,
]);

export const OperatorSubscriptionNeq = {
  Neq: "neq",
} as const;
export type OperatorSubscriptionNeq = ClosedEnum<
  typeof OperatorSubscriptionNeq
>;

export const OperatorSubscriptionNeq$zodSchema = z.enum([
  "neq",
]);

export const OperatorSubscriptionEq = {
  Eq: "eq",
} as const;
export type OperatorSubscriptionEq = ClosedEnum<typeof OperatorSubscriptionEq>;

export const OperatorSubscriptionEq$zodSchema = z.enum([
  "eq",
]);

export const OperatorSubscriptionLte = {
  Lte: "lte",
} as const;
export type OperatorSubscriptionLte = ClosedEnum<
  typeof OperatorSubscriptionLte
>;

export const OperatorSubscriptionLte$zodSchema = z.enum([
  "lte",
]);

export const OperatorSubscriptionLt = {
  Lt: "lt",
} as const;
export type OperatorSubscriptionLt = ClosedEnum<typeof OperatorSubscriptionLt>;

export const OperatorSubscriptionLt$zodSchema = z.enum([
  "lt",
]);

export const OperatorSubscriptionGte = {
  Gte: "gte",
} as const;
export type OperatorSubscriptionGte = ClosedEnum<
  typeof OperatorSubscriptionGte
>;

export const OperatorSubscriptionGte$zodSchema = z.enum([
  "gte",
]);

export const OperatorSubscriptionGt = {
  Gt: "gt",
} as const;
export type OperatorSubscriptionGt = ClosedEnum<typeof OperatorSubscriptionGt>;

export const OperatorSubscriptionGt$zodSchema = z.enum([
  "gt",
]);

export type SubscriptionOperatorUnion =
  | OperatorSubscriptionGt
  | OperatorSubscriptionGte
  | OperatorSubscriptionLt
  | OperatorSubscriptionLte
  | OperatorSubscriptionEq
  | OperatorSubscriptionNeq;

export const SubscriptionOperatorUnion$zodSchema: z.ZodType<
  SubscriptionOperatorUnion
> = z.union([
  OperatorSubscriptionGt$zodSchema,
  OperatorSubscriptionGte$zodSchema,
  OperatorSubscriptionLt$zodSchema,
  OperatorSubscriptionLte$zodSchema,
  OperatorSubscriptionEq$zodSchema,
  OperatorSubscriptionNeq$zodSchema,
]);

export type SubscriptionConditions = {
  field: string;
  operator:
    | OperatorSubscriptionGt
    | OperatorSubscriptionGte
    | OperatorSubscriptionLt
    | OperatorSubscriptionLte
    | OperatorSubscriptionEq
    | OperatorSubscriptionNeq;
  threshold: number;
};

export const SubscriptionConditions$zodSchema: z.ZodType<
  SubscriptionConditions
> = z.object({
  field: z.string(),
  operator: z.union([
    OperatorSubscriptionGt$zodSchema,
    OperatorSubscriptionGte$zodSchema,
    OperatorSubscriptionLt$zodSchema,
    OperatorSubscriptionLte$zodSchema,
    OperatorSubscriptionEq$zodSchema,
    OperatorSubscriptionNeq$zodSchema,
  ]),
  threshold: z.number(),
});

export type Subscription = {
  id: string;
  channel:
    | ChannelSubscriptionFeeds
    | ChannelSubscriptionAgentEvents
    | ChannelSubscriptionReports;
  url: string;
  filter?: { [k: string]: Array<string> } | undefined;
  conditions?: SubscriptionConditions | undefined;
  active: boolean;
  created_at: string;
};

export const Subscription$zodSchema: z.ZodType<Subscription> = z.object({
  active: z.boolean(),
  channel: z.union([
    ChannelSubscriptionFeeds$zodSchema,
    ChannelSubscriptionAgentEvents$zodSchema,
    ChannelSubscriptionReports$zodSchema,
  ]),
  conditions: z.lazy(() => SubscriptionConditions$zodSchema).optional(),
  created_at: z.string(),
  filter: z.record(z.string(), z.array(z.string())).optional(),
  id: z.string(),
  url: z.string(),
});

/**
 * Default Response
 */
export type PostV1OracleAlertsResponseBody = {
  subscription: Subscription;
  secret: string;
};

export const PostV1OracleAlertsResponseBody$zodSchema: z.ZodType<
  PostV1OracleAlertsResponseBody
> = z.object({
  secret: z.string(),
  subscription: z.lazy(() => Subscription$zodSchema),
}).describe("Default Response");

export type PostV1OracleAlertsResponse = Def0 | PostV1OracleAlertsResponseBody;

export const PostV1OracleAlertsResponse$zodSchema: z.ZodType<
  PostV1OracleAlertsResponse
> = z.union([
  Def0$zodSchema,
  z.lazy(() => PostV1OracleAlertsResponseBody$zodSchema),
]);
