/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Def0, Def0$zodSchema } from "./def0.js";

/**
 * Default Response
 */
export type PostV1OracleStreamTokenResponseBody = {
  token: string;
  expiresIn: number;
};

export const PostV1OracleStreamTokenResponseBody$zodSchema: z.ZodType<
  PostV1OracleStreamTokenResponseBody
> = z.object({
  expiresIn: z.int(),
  token: z.string(),
}).describe("Default Response");

export type PostV1OracleStreamTokenResponse =
  | Def0
  | PostV1OracleStreamTokenResponseBody;

export const PostV1OracleStreamTokenResponse$zodSchema: z.ZodType<
  PostV1OracleStreamTokenResponse
> = z.union([
  Def0$zodSchema,
  z.lazy(() => PostV1OracleStreamTokenResponseBody$zodSchema),
]);
