/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { Def0, Def0$zodSchema } from "./def0.js";

export type SignatureRequest = { signer: string; sig: string };

export const SignatureRequest$zodSchema: z.ZodType<SignatureRequest> = z.object(
  {
    sig: z.string(),
    signer: z.string(),
  },
);

export type PostV1OracleReportsVerifyReport = {
  feed_id: string;
  feed_version: number;
  report_timestamp: number;
  values: { [k: string]: any };
  input_manifest_hash: string;
  computation_hash: string;
  revision: number;
  signer_set_id: string;
  signatures: Array<SignatureRequest>;
};

export const PostV1OracleReportsVerifyReport$zodSchema: z.ZodType<
  PostV1OracleReportsVerifyReport
> = z.object({
  computation_hash: z.string(),
  feed_id: z.string(),
  feed_version: z.int(),
  input_manifest_hash: z.string(),
  report_timestamp: z.number(),
  revision: z.int(),
  signatures: z.array(z.lazy(() => SignatureRequest$zodSchema)),
  signer_set_id: z.string(),
  values: z.record(z.string(), z.any()),
});

export type PostV1OracleReportsVerifyRequest = {
  report: PostV1OracleReportsVerifyReport;
};

export const PostV1OracleReportsVerifyRequest$zodSchema: z.ZodType<
  PostV1OracleReportsVerifyRequest
> = z.object({
  report: z.lazy(() => PostV1OracleReportsVerifyReport$zodSchema),
});

export const SignatureFail = {
  Fail: "fail",
} as const;
export type SignatureFail = ClosedEnum<typeof SignatureFail>;

export const SignatureFail$zodSchema = z.enum([
  "fail",
]);

export const SignaturePass = {
  Pass: "pass",
} as const;
export type SignaturePass = ClosedEnum<typeof SignaturePass>;

export const SignaturePass$zodSchema = z.enum([
  "pass",
]);

export type Signature = SignaturePass | SignatureFail;

export const Signature$zodSchema: z.ZodType<Signature> = z.union([
  SignaturePass$zodSchema,
  SignatureFail$zodSchema,
]);

export const PayloadIntegrityFail = {
  Fail: "fail",
} as const;
export type PayloadIntegrityFail = ClosedEnum<typeof PayloadIntegrityFail>;

export const PayloadIntegrityFail$zodSchema = z.enum([
  "fail",
]);

export const PayloadIntegrityPass = {
  Pass: "pass",
} as const;
export type PayloadIntegrityPass = ClosedEnum<typeof PayloadIntegrityPass>;

export const PayloadIntegrityPass$zodSchema = z.enum([
  "pass",
]);

export type PayloadIntegrity = PayloadIntegrityPass | PayloadIntegrityFail;

export const PayloadIntegrity$zodSchema: z.ZodType<PayloadIntegrity> = z.union([
  PayloadIntegrityPass$zodSchema,
  PayloadIntegrityFail$zodSchema,
]);

export type Checks = {
  signature: SignaturePass | SignatureFail;
  payload_integrity: PayloadIntegrityPass | PayloadIntegrityFail;
  signer_set_id: string;
  signers: Array<string>;
};

export const Checks$zodSchema: z.ZodType<Checks> = z.object({
  payload_integrity: z.union([
    PayloadIntegrityPass$zodSchema,
    PayloadIntegrityFail$zodSchema,
  ]),
  signature: z.union([
    SignaturePass$zodSchema,
    SignatureFail$zodSchema,
  ]),
  signer_set_id: z.string(),
  signers: z.array(z.string()),
});

export type Publication = { solana_tx: string | null; base_tx: string | null };

export const Publication$zodSchema: z.ZodType<Publication> = z.object({
  base_tx: z.string().nullable(),
  solana_tx: z.string().nullable(),
});

export type PostV1OracleReportsVerifyData = {
  valid: boolean;
  checks: Checks;
  publication: Publication;
};

export const PostV1OracleReportsVerifyData$zodSchema: z.ZodType<
  PostV1OracleReportsVerifyData
> = z.object({
  checks: z.lazy(() => Checks$zodSchema),
  publication: z.lazy(() => Publication$zodSchema),
  valid: z.boolean(),
});

/**
 * Default Response
 */
export type PostV1OracleReportsVerifyResponseBody = {
  data: PostV1OracleReportsVerifyData;
};

export const PostV1OracleReportsVerifyResponseBody$zodSchema: z.ZodType<
  PostV1OracleReportsVerifyResponseBody
> = z.object({
  data: z.lazy(() => PostV1OracleReportsVerifyData$zodSchema),
}).describe("Default Response");

export type PostV1OracleReportsVerifyResponse =
  | Def0
  | PostV1OracleReportsVerifyResponseBody;

export const PostV1OracleReportsVerifyResponse$zodSchema: z.ZodType<
  PostV1OracleReportsVerifyResponse
> = z.union([
  Def0$zodSchema,
  z.lazy(() => PostV1OracleReportsVerifyResponseBody$zodSchema),
]);
