/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type Security = { apiKey: string };

export const Security$zodSchema: z.ZodType<Security> = z.object({
  apiKey: z.string().describe(
    "API key for authenticated access. Determines plan tier (free/pro/growth).",
  ),
});
